server:
  address: :8080
  use_tls: true
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"
  redirect_http: true
  http_redirect_port: ":80"

routes:
  - path: /api
    backend: http://localhost:9000
    strip_prefix: false
    match_type: prefix_match
  - path: /git
    backend: https://github.com/SayantanSaha/toron
    strip_prefix: true
  - path: /ui
    backend: ./webui